* Bon app launcher for Emacs
  Dmenu-like application launcher generally designed for EXWM.

  In a nutshell it just lists all binary files under PATH variable entries through *ivy-read* (if *ivy* package is present)
  and runs the shell command with *start-process-shell-command*.
  It also by default preselects the last chosen entry.

** About
   The package intends to bring dmenu features to GNU Emacs editor used as a Desktop Environment.
   For some reason other application launchers for Emacs (like *counsel-linux-app*) do not allow to run custom shell command or pass some options to the programs (as dmenu does) and at the same time the default EXWM app launcher, which allows running shell commands, does not have an interactive menu.
   So *bon-app-launcher* is an Emacs-addopted dmenu clone with two additional features:
   1. Autoselecting last chosen entry
   2. Sorting most used entries to the beggining of the list
   
** Getting started
   Cloning the repo:
#+begin_src sh
git clone https://github.com/slamko/bon-app-launcher.git
#+end_src

   Loading package:
#+begin_src emacs-lisp
(add-to-list 'load-path "*cloned repo path*")
(require 'bon-app-launcher)
#+end_src

Alternatively using *straight*
#+begin_src emacs-lisp
(use-package bon-app-launcher
  :commands (bon-app-launcher bon-app-launcher-usr-bin)
  :straight (bon-app-launcher :host github
                    :repo "slamko/bon-app-launcher"))
#+end_src

   Also it is a popular practice for window managers to bind the app launcher to *Super + P*:
#+begin_src emacs-lisp
(exwm-input-set-key (kbd "s-p") 'bon-app-launcher)
#+end_src

