* Bon app launcher for Emacs
  Dmenu-like application launcher generally designed for EXWM.

  In a nutshell it just lists all binary files under PATH variable entries through *ivy-read* (if *ivy* package is present)
  and runs the shell command with *start-process-shell-command*.
  It also by default preselects the last chosen entry.

** Why?
   Mainly to bring dmenu into the Emacs as a Desktop.
   1. The way that EXWM offers to run applications is just a shell prompt with no interactive menu (which is bad).
   2. Other options such as *counsel-linux-app* or *app-launcher* by System Crafters for some reason show only "desktop" applications in the list
	  or do not allow to pass custom options to the program.

   *Bon app launcher* on the other hand aims to bring the simplicity of dmenu and the power of the shell prompt.

** Getting started
   Cloning the repo:
#+begin_src sh
git clone https://github.com/slamko/bon-app-launcher.git
#+end_src

   Loading package:
#+begin_src emacs-lisp
(add-to-list 'load-path "*cloned repo path*")
(require 'bon-app-launcher)
#+end_src

   Also it is a popular practice for window managers to bind the app launcher to *Super + P*:
#+begin_src emacs-lisp
(exwm-input-set-key (kbd "s-p") 'bon-app-launcher)
#+end_src
